import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useState, useEffect } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export function getStaticPaths() {
  return fetch(
    "https://nosservicespublics.getgrist.com/api/docs/hXBbY6ngk5ik/tables/Thematiques/records",
  )
    .then((r) => r.json())
    .then((r) => r.records)
    .then((records) => {
      return {
        paths: records.map((r) => {
          return { params: { id: r.fields.Nom_technique } };
        }),
        fallback: true,
      };
    });

  return { paths: [{ params: { id: "education" } }], fallback: true };
}

export function getStaticProps() {
  return { props: {} };
}

export default function Home() {
  const router = useRouter();

  const [thematique, setThematique] = useState();
  const [questions, setQuestions] = useState([]);
  const [reponses, setReponses] = useState([]);
  useEffect(() => {
    if (!router.query.id) {
      return;
    }
    fetch(
      `https://nosservicespublics.getgrist.com/api/docs/hXBbY6ngk5ik/tables/Thematiques/records?filter={"Nom_technique": ["${router.query.id}"]}`,
    )
      .then((r) => r.json())
      .then((r) => r.records)
      .then((records) => {
        setThematique(records[0]);
        return records[0];
      })
      .then((thematique) => {
        fetch(
          `https://nosservicespublics.getgrist.com/api/docs/hXBbY6ngk5ik/tables/Questions/records?filter={"Thematique": [${thematique.id}]}`,
        )
          .then((r) => r.json())
          .then((r) => r.records)
          .then(setQuestions);
        fetch(
          `https://nosservicespublics.getgrist.com/api/docs/hXBbY6ngk5ik/tables/Reponses/records?filter={"Thematique": [${thematique.id}]}`,
        )
          .then((r) => r.json())
          .then((r) => r.records)
          .then(setReponses);
      });
  }, [router.query]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{thematique?.fields.Nom}</h1>
        {questions?.map((question) => {
          return <p key={question.id}>{question.fields.Intitule}</p>;
        })}
        <div>
          {reponses?.map((reponse) => {
            return <p key={reponse.id}>{reponse.fields.Chapo}</p>;
          })}
        </div>
      </main>
    </>
  );
}
