import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [themes, setThemes] = useState([]);
  useEffect(() => {
    fetch(
      "https://nosservicespublics.getgrist.com/api/docs/hXBbY6ngk5ik/tables/Thematiques/records",
    )
      .then((r) => r.json())
      .then((r) => r.records)
      .then(setThemes);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {themes?.map((theme) => {
          return (
            <a
              key={theme.fields.Nom_technique}
              href={`/theme/${theme.fields.Nom_technique}`}
            >
              {theme.fields.Nom} ({theme.fields.Nombres_de_questions} questions)
            </a>
          );
        })}
        <a href="a-propos">À propos (TODO)</a>
      </main>
    </>
  );
}
